### ISSUE TITLE
Beyond glyph set will not be updated before 2024 - right?

### ISSUE THREAD

**Issue by EbenSorkin** [googlefonts/glyphsets#148]
I think the Beyond Glyphs set my see movement like we have had with SSA and Beyond but I suspect that that will be dealt with in 2024 at the soonest. Is this a fair assessment of what is likely to happen? I ask because I am targeting the existing Beyond glyph set for Merriweather.

**Comment by moyogo** [comment]
The Beyond glyphset needs to be reviewed but basically it can be generated with a glyphset definition yaml file (with #109, #142). There are quite a few characters that are being moved out of GF Latin African that belong in GF Latin Beyond.

```yaml
use_auxiliary: true
extends:
- GF Latin African
- GF Latin Vietnamese
language_codes:
- etc. # list of language codes here
```

The long list of languages can be generated with `scripts/assemble_languages.py`.

The quality of the character set will depend on the quality of the data in gflanguages.
